# base
seed: 0
deterministic: True

# environment config
device: cpu     # examples: [0], [0,1], [1,2,3], cpu, mps... 

# project config
project: outputs/resnet_wo_zeropad
name: CIFAR10

# model config
model_type: resnet        # [resnet, cnn] If resnet, ResNet will be loaded, else, vanilla CNN will be loaded.
num_layer: 3              # Number of each residual block's layer. A model consisting of a total of (num_layer * 2 * 3 + 2) layers will be created.
zero_padding: False       # For downsampling in the shortcuts, use zero padding if True, and a 1x1 convolutional layer if False.

# image setting config
height: 32
width: 32
color_channel: 3
convert2grayscale: False

# data config
workers: 0               # Don't worry to set worker. The number of workers will be set automatically according to the batch size.
CIFAR10_train: True      # if True, CIFAR10 will be loaded automatically.
class_num: 10            # Number of image label classes.
CIFAR10:
    path: data/
    CIFAR10_valset_proportion: 0.2      # CIFAR10 has only train and test data. Thus, part of the training data is used as a validation set.
CUSTOM:
    train_data_path: null
    validation_data_path: null
    test_data_path: null

# train config
batch_size: 128
steps: 64000
warmup_steps: 100
lr0: 0.001
lrf: 0.001                  # last_lr = lr0 * lrf
scheduler_type: 'cosine'    # ['linear', 'cosine']
momentum: 0.9
weight_decay: 0.0
warmup_momentum: 0.8


# prediction result visualzation config
result_num: 10              # number of prediction results to be shown

# logging config
common: ['train_loss', 'train_acc', 'validation_loss', 'validation_acc', 'lr']